apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: discovery
  title: Discovery
  description: Search, store pages, categories, deals, and coupons
  tags:
    - search
    - stores
    - coupons
spec:
  owner: group:product-team
  type: product-area
